# Generated by Django 3.1 on 2020-09-11 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
