# Generated by Django 3.1 on 2020-09-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_customerinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=50)),
                ('description', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
