# Generated by Django 3.1 on 2020-09-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttype',
            name='slug',
            field=models.CharField(default='', max_length=100),
        ),
    ]
