# Generated by Django 3.1 on 2020-10-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_producttype_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_img',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='img/product', verbose_name='Product_IMG'),
        ),
    ]
