# Generated by Django 3.1 on 2020-09-13 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='categories',
            name='parent_category',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='sort_order',
        ),
    ]
