# Generated by Django 3.1 on 2020-10-11 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='feature_img',
            field=models.ImageField(blank=True, max_length=254, null=True, upload_to='img/news/2020/10', verbose_name='Feature Image'),
        ),
        migrations.AlterField(
            model_name='news',
            name='short_description',
            field=models.TextField(max_length=150, verbose_name='Short description'),
        ),
    ]
