# Generated by Django 3.1 on 2020-08-24 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='customeruser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='customeruser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='email',
            field=models.EmailField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
